### ISSUE TITLE
Single Color LED controller 

### ISSUE THREAD

**Issue by rubenverhoef** [happyleavesaoc/python-limitlessled#27]
I have a single color MiLight led controller and i can't get it to work with python-limitlessled. I'm running the following python code:

```
from limitlessled.bridge import Bridge
from limitlessled.group.rgbw import RGBW
from limitlessled.group.rgbww import RGBWW
from limitlessled.group.white import WHITE

bridge = Bridge('192.168.0.42')
# A group number can support two groups as long as the types differ
bridge.add_group(1, 'hoek', WHITE)

hoek = bridge.add_group(1, 'hoek', WHITE)

hoek.on = True

```

Does someone has any idea? is the single color led controller supported?
![image](https://user-images.githubusercontent.com/9071284/35937288-131cdfe6-0c46-11e8-930f-aa8d80fa2a0f.png)

**Comment by rubenverhoef** [comment]
Okay, i sorted things out. I have record the network packages and this unit uses 0x03 as remote style. I have add support for this in the software and i'm going to test this. If it works i will make a pull request.

**Comment by happyleavesaoc** [comment]
@rubenverhoef That would be great!

**Comment by duecedriver** [comment]
the FUT036 is indeed the strip controller I use in question.

what does the 0x03 remote look like.. ?  just from the iOS app emulation.  I can get this strip controller to work with several of them on the ios app.. but home assistant is a bit more obtuse.

this is the 'virtual remote' that I use to pair my RGBWW and these fut036 strip controllers for home assistant because nothing else seems to work

http://www.limitlessled.com/wp-content/uploads/2017/01/LimitlessLEDrgbwwwcwWallRemote.jpg

I use this remote for the rgbw pairing...

http://www.limitlessled.com/shop/remote-control-for-rgbw-color-led-lightbulbs/

this is the remote that the strip controller shoud be paired with I think

http://www.limitlessled.com/shop/wifi-remote/

but if I pair with this remote i only get on/off supprort in homebridge.. no dimmer at all.

**Comment by amelchio** [comment]
Please don't cross-post, let's keep this in home-assistant/home-assistant#12907

**Comment by duecedriver** [comment]
ok I have deleted my post here but you already closed 12907... so what is the resolution?
